from __future__ import print_function
import os
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
from vvpages.models import Page


class Command(BaseCommand):
    help = 'Build navigation links for vvpages'

    def handle(self, *args, **options):
        pages = Page.objects.filter(level=1, published=True)
        print("Building navigation ...")
        navlinks = ["{# ************ Autogenerated file: do not edit ************ #}"]
        i = 1
        for page in pages:
            val = '<li><a class="btn btn-link" href="'+page.url.replace("%2F", "")+'">'+page.title+'</a></li>'
            navlinks.append(val)
            print(str(i)+": "+page.url)
            i += 1
        navlinks_str = '\n'.join(navlinks)
        # check directories
        dirpath = settings.BASE_DIR+"/templates/vvpages"
        if not os.path.isdir(dirpath) is True:
            print("Creating directory templates/vvpages")
            os.makedirs(dirpath)
        dirpath = settings.BASE_DIR+"/templates/vvpages/auto"
        if not os.path.isdir(dirpath) is True:
            os.makedirs(dirpath)
            print("Creating directory templates/vvpages/auto")
        # update
        filepath=settings.BASE_DIR+"/templates/vvpages/auto/navlinks.html"
        print("Updating templates/vvpages/auto/navlinks.html")
        #~ write the file
        filex = open(filepath, "w")
        filex.write(navlinks_str)
        filex.close()
        print("OK: "+str(i-1)+" navlinks built")
        return
