# -*- coding: utf-8 -*-

import os
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings
from vvpages.models import Page
from django.core.urlresolvers import reverse


class Command(BaseCommand):
    help = 'Build routes for vvpages'

    def handle(self, *args, **options):
        pages = Page.objects.filter(published=True)
        print "Building routes ..."
        routes = []
        i = 1
        for page in pages:
            rest_url = reverse("vvpages-rest", kwargs={'pk':page.pk})
            #rest_url = "/pages/rest/"+str(page.pk)+"/"
            val = "page('"+page.url+"', function(ctx, next) { app.loadHtml('"+rest_url+"') } );"
            routes.append(val)
            print str(i)+": "+page.url
            i += 1
        routes_str = '{# ************ Autogenerated file: do not edit ************ #}\n'+'\n'.join(routes)
        # check directories
        dirpath = settings.BASE_DIR+"/templates/vvpages"
        if not os.path.isdir(dirpath) is True:
            print "Creating directory templates/vvpages"
            os.makedirs(dirpath)
        dirpath = settings.BASE_DIR+"/templates/vvpages/auto"
        if not os.path.isdir(dirpath) is True:
            os.makedirs(dirpath)
            print "Creating directory templates/vvpages/auto"
        # update
        filepath=settings.BASE_DIR+"/templates/vvpages/auto/routes.js"
        print "Updating templates/vvpages/auto/routes.js"
        #~ write the file
        filex = open(filepath, "w")
        filex.write(routes_str)
        filex.close()
        print "OK: "+str(i-1)+" routes built "
        return
