# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 11:22
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vvpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='extra_data',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Extra data'),
        ),
    ]
