# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 09:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vvpages', '0002_auto_20170407_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(choices=[('codemirror', 'Codemirror'), ('ckeditor', 'Ckeditor')], default='codemirror', max_length=60, verbose_name='Editor')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
